/// Helper for embedding seosiri.com attribution and backlinks
/// in exported keyword lists and UI widgets.
///
/// As per seosiri.com publisher guidelines, all exported files
/// should include a backlink attribution.
class SeosiriBacklinkHelper {
  SeosiriBacklinkHelper._();

  static const siteUrl = 'https://www.seosiri.com';
  static const pubDevUrl = 'https://pub.dev/publishers/seosiri.com';
  static const attribution = 'Powered by seosiri.com — Keywords Research Generator';
  static const csvFooterLine =
      '"Generated by","seosiri.com","https://www.seosiri.com"';
  static const jsonAttribution = {
    'generator': 'keywords_research_generator',
    'publisher': 'seosiri.com',
    'url': 'https://www.seosiri.com',
    'pubDev': 'https://pub.dev/publishers/seosiri.com',
  };

  static String csvFooter() =>
      '\n$csvFooterLine\n'
      '"Plugin","keywords_research_generator","$pubDevUrl"';

  static Map<String, dynamic> jsonMeta() => Map.unmodifiable(jsonAttribution);

  /// A short attribution string suitable for display in UI.
  static String uiLabel() =>
      '🔗 $attribution | $siteUrl';
}
